---
apiVersion: v1
kind: DeploymentConfig
metadata: 
  name: api
  labels: 
      name: api
spec:
  replicas: 1
  template:
    metadata:
      name: api
      labels:
        app: api      
    spec:
      containers: 
        - env:
            - name: API_PORT
              value: "8080"
            - name: STORAGE_BACKEND
              value: "boltdb"
            - name: BOLTDB_LOCATION
              value: "/tmp/test.db"
          image: mangirdas/ocp-example-api:v0.5
          imagePullPolicy: Always
          name: api
          command: ["/bin/api"]
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              # Path to probe; should be cheap, but representative of typical behavior
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
        - env:
            - name: API_MON_PORT
              value: "8081"
            - name: API_PORT
              value: "8080"
            - name: API_IP
              value: http://0.0.0.0
          image: mangirdas/ocp-example-api-mon:v0.5
          imagePullPolicy: Always
          name: api-mon
          command: ["/bin/api"]
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              # Path to probe; should be cheap, but representative of typical behavior
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            timeoutSeconds: 1      
          livenessProbe:
            httpGet:
              # Path to probe; should be cheap, but representative of typical behavior
              path: /readiness
              port: 8081
            initialDelaySeconds: 15
            timeoutSeconds: 1      