apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: fe
    labels:
      app: fe
  spec:
    ports:
    - name: http
      port: 8080
    selector:
      app: fe
- apiVersion: v1
  kind: Service
  metadata:
    name: api-svc
    labels:
      app: api
  spec:
    ports:
    - name: http
      port: 8080
    selector:
      app: api
- apiVersion: v1
  kind: Service
  metadata:
    name: img-svc
    labels:
      app: img
  spec:
    ports:
    - name: http
      port: 8080
    selector:
      app: img      